services:
  app:
    build:
      context: .            # Aponta para a raiz do projeto
      # dockerfile: .devcontainer/Dockerfile
      dockerfile: Dockerfile
    networks:
      - fakeshop_net
    environment:
      DB_DATABASE: fakeshop
      DB_USERNAME: fakeshop
      DB_PASSWORD: pg1234
      DB_HOST: db

  db:
    image: postgres:13.13
    networks:
      - fakeshop_net
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: fakeshop
      POSTGRES_DB: fakeshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  fakeshop_net:
    driver: bridge

volumes:
  postgres_data: