services:
  app:
    build: .                # Usa o Dockerfile da raiz
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg1234
      DB_HOST: db
    ports:
      - 80:8080             # Porta padrão HTTP
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.13
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubenews -d kubenews"]

volumes:
  postgres_data: