version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached    
    command: sleep infinity
    networks:
      - kubenews_net
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg1234
      DB_HOST: db
    ports:
      - 8080:8080

  db:
    image: postgres:13.13
    restart: unless-stopped
    networks:
      - kubenews_net
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    ports:
      - 5432:5432

networks:
  kubenews_net:
    driver: bridge